# Generated by Django 5.0.3 on 2024-08-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='rating_value',
        ),
    ]
