# Generated by Django 5.1.3 on 2024-12-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_old_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='specifications',
            name='additional_specifications',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
