# Generated by Django 5.0.3 on 2024-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_rating_comment_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifications',
            name='additional_specifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
