# Generated by Django 5.0.3 on 2024-05-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_color_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='old_price',
        ),
    ]
