# Generated by Django 5.1.3 on 2025-01-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_color_options_rename_color_name_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage',
            field=models.PositiveSmallIntegerField(help_text='In GB'),
        ),
    ]
