# Generated by Django 5.0.3 on 2024-05-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_original_price_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='storages',
        ),
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='core.product'),
        ),
    ]
