# Generated by Django 5.1.3 on 2025-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_sales_alter_storage_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
