# Generated by Django 5.1.3 on 2025-01-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifications',
            name='chip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
