# Generated by Django 5.1.3 on 2025-02-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_specifications_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The price that will be added to the price of the product'),
        ),
    ]
