# Generated by Django 5.0.3 on 2024-05-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_producttype_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='type',
            new_name='title',
        ),
    ]
