# Generated by Django 5.1.3 on 2025-02-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_sales_product_sold_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='price',
            new_name='add_price',
        ),
    ]
