# Generated by Django 5.0.3 on 2024-06-02 12:44

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.ForeignKey(default=core.models.Rating.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.rating'),
        ),
    ]
