# Generated by Django 5.0.3 on 2024-06-05 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.color'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storage'),
        ),
    ]
