# Generated by Django 5.0.3 on 2024-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_productversion_user_alter_productversion_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
