# Generated by Django 5.0.3 on 2024-06-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_product_rating_alter_storage_price_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='is_default',
        ),
    ]
