# Generated by Django 5.0.3 on 2024-06-05 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_address_delete_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='core.product'),
        ),
    ]
