# Generated by Django 5.0.3 on 2024-06-17 23:00

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_storage_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.ForeignKey(blank=True, default=core.models.Rating.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.rating'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.color'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.storage'),
        ),
    ]
