# Generated by Django 5.0.3 on 2024-06-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_street_address_address_remove_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='flat',
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
