# Generated by Django 5.0.3 on 2024-07-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_cart_created_at_favorite_created_at_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
