# Generated by Django 5.0.3 on 2024-07-14 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_productversion_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('cellular_technology', models.CharField(blank=True, max_length=100, null=True)),
                ('display_type', models.CharField(blank=True, max_length=100, null=True)),
                ('camera', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('battery', models.CharField(blank=True, max_length=100, null=True)),
                ('water_and_dust_rating', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Specifications',
                'verbose_name_plural': 'Specifications',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='core.cart')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.specifications'),
        ),
    ]
