# Generated by Django 5.0.3 on 2024-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_specifications_order_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifications',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
