# Generated by Django 5.0.3 on 2024-07-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
    ]
