# Generated by Django 5.0.3 on 2024-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_order_payment_method_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='carts', to='core.productversion'),
        ),
    ]
